[WIP] Combine Upscale classes
LLNL/smoothG pull request #33
Opened 2018-10-29 16:58 UTC by chakshinglee

Because the core part of all the *Upscale classes are essentially the same (the differences being how we construct the distributed graph and treatment of boundary conditions), this PR collapses them into Upscale. The benefit is to avoid changing all the *Upscale files whenever there is some update to Topology/Coarsener/Solver. 

This is still WIP. I branched it out from `feature/ml-coarsen`, which is a branch started very long time ago (Feb), and I recently merged it with the current master, so there are quite many conflicts.

2018-11-06 00:10 UTC, chakshinglee commented on examples/stest.py
> +          "max-p-error": 0.39869063097389679}]
@barker29 In some PR you raised the concern on this mismatch. Does this update match with test result on your machine (up to `1e-4`)? While working on this PR, I realize that the test tolerance on travis is `1e-2` while the default tolerance specified in CMakeLists.txt is `1e-4`, I guess that's why the test is passing on travis but not on our machines.

2018-11-06 00:12 UTC, chakshinglee commented on examples/CMakeLists.txt
> +    set(SMOOTHG_TEST_PROCS 2)
@barker29 The test results on parallel graph now depend on number of processors, so I match this with the value set on travis.

2018-11-15 18:26 UTC, barker29 commented
I haven't looked very closely, but my first concern is that the errors in many of the tests are much higher in this PR. Is this just because of the number of processors? I don't like an error of 0.8, to me this feels like the algorithm is somehow not working.

2018-11-16 22:27 UTC, barker29 requested changes
This is a lot of work and a big improvement.

The only thing I'm really worried about is the change in errors in all the tests - I want to understand what is causing this before I approve.

2018-11-16 22:27 UTC, barker29 commented on src/Upscale.hpp
> +    Upscale(const Graph& graph,
Can we get a line of documentation for each of these constructors? (also, it might be possible to combine a couple of them by using more default arguments?)

2018-11-16 22:27 UTC, barker29 commented on src/MixedMatrix.hpp
> +    MixedMatrix(const Graph& graph, const mfem::SparseMatrix& w_block = SparseIdentity(0));
This is a very nice simplification (in general your use of the `Graph` object is very nice and simplifies a lot!)

2018-11-16 22:27 UTC, barker29 commented on src/LocalMixedGraphSpectralTargets.hpp
> +    LocalMixedGraphSpectralTargets(
One line of documentation please (this one is actually a bit different from the other constructors, at least the calling sequence).

2018-11-16 22:27 UTC, barker29 commented on src/LocalMixedGraphSpectralTargets.hpp
> +    enum DofType { vdof, edof }; // vertex-based and edge-based dofs
I think maybe `vdof` should be `VDOF` - that's the style I usually see for `enum`, but I guess we can make our own decision. What do you think?

2018-11-16 22:27 UTC, barker29 commented on src/GraphTopology.hpp
> +                  const mfem::HypreParMatrix& edge_trueedge,
These name changes are much better than before.

2018-11-16 22:27 UTC, barker29 commented on examples/stest.py
> +          "finest-p-error": 0.80196594708999625,
As I said in a previous comment, these errors seem really quite high. I want to understand why before I approve this PR.

2018-11-16 22:27 UTC, barker29 commented on examples/stest.py
> +          "max-p-error": 0.39869063097389679}]
Yes, this matches.

2018-11-16 22:27 UTC, barker29 commented on examples/stest.py
> +    tests["parsamplegraph1-coeff-mac"] = \
These `-mac` tests are starting to get a bit out of hand. I'd like to have consistent tests that don't depend on platform, but that's probably a harder task and anyway would be a totally different PR.

2018-11-16 22:27 UTC, barker29 commented on src/Graph.cpp
> + * LLNL-CODE-XXXXXX. All Rights reserved.
This should have the correct release number (in general this should be done before anything is put on GitHub, even in a branch).

2018-11-16 22:27 UTC, barker29 commented on src/Graph.cpp
> + * For more information and source code availability see XXXXX.
replace XXXXX

2018-11-16 22:27 UTC, barker29 commented on src/Graph.hpp
> + * LLNL-CODE-XXXXXX. All Rights reserved.
release number.

2018-11-16 22:27 UTC, barker29 commented on src/Graph.hpp
> +    HypreParMatrix edge_e_te
```suggestion
    HypreParMatrix edge_trueedge
```

2018-11-16 22:27 UTC, barker29 commented on src/Graph.hpp
> +       between processors, which is encoded in edge_e_te_.
```suggestion
       between processors, which is encoded in edge_trueedge_.
```

2018-11-16 22:27 UTC, barker29 commented on src/Graph.hpp
> +    Graph(const mfem::SparseMatrix& vertex_edge_local,
A line of documentation please (it's fine to have thorough documentation for one constructor and short doc for the others, but they should all have something.)

2018-11-16 22:27 UTC, barker29 commented on src/Graph.hpp
> +    Graph(const mfem::SparseMatrix& vertex_edge_local,
Document.

2018-11-16 22:27 UTC, barker29 commented on src/Graph.cpp
> +    if (edge_weight_local)
`edge_weight_local` is a reference here, not a pointer, I'm not sure this will do what you expect. Maybe `if (edge_weight_local.Size() > 0)` ?

2018-11-16 22:27 UTC, barker29 commented on src/LocalMixedGraphSpectralTargets.cpp
>      // Gelever uses face_trueface rather than facedof_truedof (?) (I think one of us is just labeling it wrong)
```suggestion
```

2018-11-16 22:27 UTC, barker29 commented on src/LocalMixedGraphSpectralTargets.cpp
>  void LocalMixedGraphSpectralTargets::ComputeVertexTargets(
You've managed to both add functionality and make this simpler and easier to read, which is impressive.

2018-11-16 22:27 UTC, barker29 commented on src/GraphTopology.hpp
> +                  const mfem::HypreParMatrix& edge_trueedge,
Modify documentation above to match name change.

2018-11-19 23:19 UTC, chakshinglee commented
@barker29 I understand your concern on the huge difference in the upscaling errors. I noticed this too when I change them, and I was also surprised by the results. Here is some more info:

An observation that suggests the code is working properly:
One way to make the partition in parallel run to be same as serial run would be to use 12 processors because serial run partition the global graph into 12 partitions. I observe the same results in parallel and serial runs (up to 8 digits) if this partition is used. 

The partition when number of processors = 2 is bad (uneven):
One thing I just checked is that, the sizes of the distributed graphs are very different when 2 processes (in our tests) are used. One processor has 75 vertices, while the other gets 925. 

Right now, the number of partitions locally is set to the intended number of global partitions divided by number of processors. Based on the above split (79, 925), we can expect pretty poor partition if we divide each local graph into 6 partitions.

If I set the number of local partitions to be also proportional to relative local graph size (effectively consider "coarsening factor"). Then the errors get better (about 55% for different error measures). 

To make sure it is really just the partitioning that is causing the difference, I dont mind going back to our original partitioning method -- partition global graph, and distribute according to the global partition. This is not the main purpose of the PR anyway. I changed the partitioning method because I extracted `Graph` out, and and I think it doesn't make sense to have partition as a member of `Graph` objects. We can make this change in a separate PR. What do you think?

Another thing is, as I mentioned to you earlier, once we add the "redistribution" code, we can use the global partition to redistribute in parallel run, then we should expect the same upscale errors as before (since the partitioning should be the same). This option would be another PR also.

2018-11-20 00:29 UTC, chakshinglee commented on src/Upscale.hpp
> +    Upscale(const Graph& graph,
You are right, I can use more default arguments. In a newer version only one constructor is left

2018-11-20 01:16 UTC, chakshinglee commented on src/Graph.cpp
> +    if (edge_weight_local)
Good catch, what you said should be the right way.

2018-11-20 01:25 UTC, chakshinglee commented on src/LocalMixedGraphSpectralTargets.hpp
> +    enum DofType { vdof, edof }; // vertex-based and edge-based dofs
Sounds good to me, this will be updated.

2018-11-26 22:21 UTC, barker29 approved these changes
Thanks for all the changes, especially the nice documentation.

Regarding the error issue, I'm convinced it's okay. In a future PR, let's changethe default so the number of local partitions is  proportional to local graph size (ie "coarsening factor"), and have the tests based on that.

2018-11-27 22:21 UTC, merged