Fix/fine edge order
LLNL/smoothG pull request #49
Opened 2019-05-24 19:46 UTC by chakshinglee

Previously we have fixed the edge ordering (all local orderings follow true ordering) when we construct a coarse graph in `GraphTopology`. Turns out when we construct graph from `mfem::ParMesh`, the ordering sometimes has problem too. So this PR is to do the same fix as in `GraphTopology`.

2019-05-24 20:30 UTC, barker29 commented
On my machine the tests `qoi` and `qoi-hb` are failing; there are seemingly significant differences in the first decimal place of the reported values. On master these tests pass. Did the random seed somehow get changed?

2019-05-28 14:42 UTC, barker29 requested changes
For now let's just rebaseline the tests (ie, change the expected results in `stest.py`) since we know what is going on, and then I will approve. I'm working on another PR that will have slightly better tests.

2019-05-28 16:55 UTC, chakshinglee commented
I just rebaselined the tests based on the value in my machine. Hopefully they match with yours.

2019-05-28 18:55 UTC, barker29 approved these changes

2019-05-28 19:43 UTC, merged