Adding FAS example
LLNL/smoothG pull request #56
Opened 2020-01-08 22:36 UTC by chakshinglee

This PR adds abstract nonlinear solver and FAS classes, as well as some concrete example and tests on elliptic problem of the form -div (K(p) grad p) = f, including Picard- and Newton-type linearizations. 

Some tests results are changed, mainly due to two changes - I flipped the x and z directions of SPE10 coefficient (the new one aligns with the original data set), and I added more edge basis to the boundary face. 

There are still two tests failing on Travis. The valgrind one should be fine - it does not show in my tuxbox, and someone on google said it will be gone for newer version of valgrind. Actually can we use newer version on Travis? The `parsamplegraph4` is NNZ problem. NNZ of coarse matrix in my tuxbox, here and my laptop are all different. I think this is due to some very small entries that are supposed to be zero. I do not know how to resolve this, maybe we need to remove the OC as one of the criteria, or use a range. 

In the case of Newton's method, the Jacobian is nonsymmetric, so the solvers are adjusted. In particular, the nonsymmetric part are added, and GMRES will be used in that case. For this reason,  `MinresBlockSolver` is simply renamed to `BlockSolver`. 

P. S. somehow github treats `BlockSolver.cpp` as a new file in the PR diff, even though git knows it was just a rename in the original commit. So for now I keep the `MinresBlockSolver.cpp` file name for review purpose (easier to see the actual modification). I will rename it back to `BlockSolver.cpp` after the review.

2020-01-10 21:17 UTC, barker29 commented
Is there a hurry to get this merged into master (ie, do you have a collaborator in mind who wants to use this)? I do want to review it, but it's a significant amount of code and I'm not sure I can get to it very soon.

2020-01-10 21:35 UTC, chakshinglee commented
It is not in a hurry. I understand this involves a large addition of codes, so please take your time. I make this PR because I am working on FAS for multiphase flow and it's good to tidy up the current code and move on.

2020-01-16 22:39 UTC, chakshinglee commented
@francoishamon thanks for agreeing to review this PR. I suggest to focus on three files: `nldarcy.cpp`, `NonlinearSolver.hpp`, and `NonlinearSolver.cpp`. Of course, feel free to comment on other changes, but they (e.g. change in test results) are probably not that relevant for the FAS project.

2020-02-12 16:42 UTC, barker29 requested changes
Overall this looks very good, there are a lot of good simplifications/improvements and the nonlinear solvers will be very useful.

The main thing I want to see before merging is for the `nldarcy` example to run with a visualization I can understand. I don't expect to understand everything you've done here but I would like this example to be clear and to make sense to me.

2020-02-12 16:42 UTC, barker29 commented on src/GraphTopology.hpp
> +    Graph Coarsen(const Graph& fine_graph, int coarsening_factor, int num_iso_verts = 0);
Can you document the purpose of the new argument?

2020-02-12 16:42 UTC, barker29 commented on src/MatrixUtilities.hpp
> +int NNZ(const mfem::SparseMatrix& mat);
I recommend removing this function (why can't the caller just call `mat.NumNonZeroElems()` which is clearer code anyway?)

2020-02-12 16:42 UTC, barker29 commented on src/MatrixUtilities.hpp
> +double FroNorm(const mfem::SparseMatrix& mat);
Let's spell this out `FrobeniusNorm` and add one line of documentation.

2020-02-12 16:42 UTC, barker29 commented on src/MetisGraphPartitioner.hpp
> +    void SetPreIsolateVertices(std::vector<std::vector<int>> sets);
The meaning of this version is pretty clear to me, but maybe not to everyone, so add a quick description to the documentation above (or a separate doc line for this method if you want).

2020-02-12 16:42 UTC, barker29 commented on src/MinresBlockSolver.cpp
> +   @brief Implements BlockSolver object.
Move this file to be `BlockSolver.cpp` (as you already did for `BlockSolver.hpp`)

2020-02-12 16:42 UTC, barker29 commented on src/MixedLaplacianSolver.hpp
> +enum KrylovMethod { CG, MINRES, GMRES };
Let's make this an [enum class](https://stackoverflow.com/questions/18335861/why-is-enum-class-preferred-over-plain-enum) and/or maybe move it inside the `MixedLaplacianSolver` class.

2020-02-12 16:42 UTC, barker29 commented on src/NonlinearSolver.hpp
> +enum Linearization { Newton, Picard };
enum class

2020-02-12 16:42 UTC, barker29 commented on src/NonlinearSolver.hpp
> +enum Cycle { V_CYCLE, FMG };
enum class

2020-02-12 16:42 UTC, barker29 commented on src/utilities.hpp
> +double AbsMax(const mfem::Vector& vec, MPI_Comm comm);
Recommend name `ParAbsMax` (it's kind of like `mfem::ParNormlp()`)

2020-02-12 16:42 UTC, barker29 commented on src/utilities.hpp
> +double Min(const mfem::Vector& vec, MPI_Comm comm);
`ParMin` or maybe `ParVectorMin`

2020-02-12 16:42 UTC, barker29 commented on examples/nldarcy.cpp
> +   @brief nonlinear Darcy's problem.
We haven't done this before, but it might be nice to have a few example command lines in the comments here (like they do in the MFEM examples). I can run this, but I am not sure what it's doing.

2020-02-12 16:42 UTC, barker29 commented on examples/nldarcy.cpp
> +        fv_problem.reset(new EggModel(num_sr, num_pr, ess_attr));
In general we are missing the files for this. We don't need to package them (like we do for SPE10) but we should at least document where they are coming from.

2020-02-12 16:42 UTC, barker29 commented on examples/nldarcy.cpp
> +        fv_problem.reset(new Richards(num_sr, ess_attr));
I can't get this model problem to run at all.

2020-02-12 16:42 UTC, barker29 commented on examples/nldarcy.cpp
> +        fv_problem.reset(new Richards(num_sr, ess_attr));
( I get some kind of GMRES breakdown, see below:)
```
Assertion failed: (IsFinite(beta)) is false:
 --> beta = inf
 ... in function: virtual void mfem::GMRESSolver::Mult(const mfem::Vector&, mfem::Vector&) const
 ... at line 570 of file: linalg/solvers.cpp
```

2020-02-12 16:42 UTC, barker29 commented on examples/nldarcy.cpp
> +    if (visualization)
I cannot get any visualization to work, I get the cryptic error:
```
Vector::Add(const double, const Vector &)
```

2020-02-12 16:42 UTC, barker29 commented on examples/pde.hpp
> +        val[i] = 1.0 / val[i];
In 2D case won't this divide by zero? (`val.Size()` is always 3)

2022-04-08 22:39 UTC, merged